### ISSUE TITLE
Proposal Proyek 2

### ISSUE THREAD

**Issue by yunitanurjanah** [SistemInformasiSewaPakaianPestaproyek2/AplikasiPengolahanDataLayananApotekTanimulyaMedika#1]
Proposal Sistem Informasi Sewa Pakaian Pesta berbasis Web (Sub Modul Pengiriman)

**Comment by yunitanurjanah** [comment]
SISTEM INFORMASI SEWA PAKAIAN PESTA BERBASIS WEB SUB MODUL PENGIRIRMAN

**Comment by awangga** [comment]
oke
