### ISSUE TITLE
Penggantian judul

### ISSUE THREAD

**Issue by yunitanurjanah** [SistemInformasiSewaPakaianPestaproyek2/AplikasiPengolahanDataLayananApotekTanimulyaMedika#2]
@awangga   Judul : Pengembangan Aplikasi Pengolahan Data menggunakan Framework Codeigniter (Study\i Kasus Klinik Tanimulya Medika (sub modul layanan   apotik)), 
[BAB I.docx](https://github.com/SistemInformasiSewaPakaianPestaproyek2/SistemInformasiSewaPakaianPestaSubPengiriman2/files/560831/BAB.I.docx)

**Comment by awangga** [comment]
oke rename nama organisasi dan proyeknya. @yunitanurjanah
